<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

/**
 * 
 *
 * @property int $id
 * @property int $project_id
 * @property string $title
 * @property string $slug
 * @property string $content
 * @property array<array-key, mixed>|null $source_references
 * @property bool $is_auto_generated
 * @property \Illuminate\Support\Carbon|null $last_updated_at
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection<int, \App\Models\WikiCategory> $categories
 * @property-read int|null $categories_count
 * @property-read \App\Models\Project $project
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage query()
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereContent($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereIsAutoGenerated($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereLastUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereProjectId($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereSourceReferences($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder<static>|WikiPage whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class WikiPage extends Model
{
    use HasFactory;

    protected $fillable = [
        'project_id',
        'title',
        'slug',
        'content',
        'source_references',
        'is_auto_generated',
        'last_updated_at',
    ];

    protected $casts = [
        'source_references' => 'array',
        'is_auto_generated' => 'boolean',
        'last_updated_at' => 'datetime',
    ];

    public function project(): BelongsTo
    {
        return $this->belongsTo(Project::class);
    }

    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(WikiCategory::class, 'wiki_category_wiki_page');
    }
    
    // Slug oluşturma
    public static function createSlug(string $title): string
    {
        return str()->slug($title);
    }
}
